# Generated by Django 4.2.4 on 2023-09-07 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
