# Generated by Django 4.2.4 on 2023-09-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="chatbot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
