# Generated by Django 4.2.4 on 2023-09-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0003_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="device",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
