# Generated by Django 4.2.4 on 2023-09-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0004_room_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="script_QA",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
