# Generated by Django 4.2.4 on 2023-10-03 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0006_question_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="project",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
