# Generated by Django 4.2.4 on 2023-10-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0008_answer_question_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="style_widget",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
