# Generated by Django 4.2.4 on 2023-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0009_project_style_widget"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="avt_img",
            field=models.ImageField(blank=True, null=True, upload_to="project_img/"),
        ),
    ]
