# Generated by Django 4.2.4 on 2023-10-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0010_project_avt_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="secretkey",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
