# Generated by Django 4.2.4 on 2023-10-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0011_project_secretkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="flow_chart",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
