# Generated by Django 4.2.4 on 2023-10-16 07:09

from django.db import migrations, models
import helpbot_backend.manage_project.models.project


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0012_project_flow_chart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="secretkey",
            field=models.CharField(
                default=helpbot_backend.manage_project.models.project.generate_random_string, max_length=50, null=True
            ),
        ),
    ]
