# Generated by Django 4.2.4 on 2023-10-16 07:09

from django.db import migrations, models
import helpbot_backend.manage_project.models.project


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0013_alter_project_secretkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="secretkey",
            field=models.CharField(
                blank=True,
                default=helpbot_backend.manage_project.models.project.generate_random_string,
                max_length=50,
                null=True,
            ),
        ),
    ]
