# Generated by Django 4.2.4 on 2023-10-20 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0015_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receiver",
            new_name="room",
        ),
    ]
