# Generated by Django 4.2.4 on 2023-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0016_rename_receiver_message_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
