# Generated by Django 4.2.4 on 2023-11-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0018_alter_answer_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
