# Generated by Django 4.2.4 on 2023-11-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manage_project", "0019_alter_message_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("idx", models.CharField(blank=True, max_length=255, null=True)),
                ("room", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="manage_project.project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
